general:
  repeats: 1000
  steps: 10000
env:
  name: Bandit
  k: 10
  shuffle: 0
algorithms:
  htmrl:
      enabled: 1
      input_size: 6
      cell_count: 2048
      active_count: 40
      boost_until: 0
      reward_window: 1000
      boost_strength: 1.0
      only_reinforce_selected: 0
      reward_scaled_reinf: 1
      normalized_rewards: 1
      boost_scaled_reinf: 0


  eps:
      enabled: 0
      e: 0.1

experiments:
  -  default:
       algorithms:
         eps:
           enabled: 1
  -  eps001:
       algorithms:
         htmrl:
           enabled: 0
         eps:
           enabled: 1
           e: 0.01
  -  longwindow:
       algorithms:
         htmrl:
           reward_window: 2000
  -  verylongwindow:
       algorithms:
         htmrl:
           reward_window: 10000
  -  small:
       algorithms:
         htmrl:
           cell_count: 100
           active_count: 10
  -  tiny:
       algorithms:
         htmrl:
           input_size: 1
           cell_count: 20
           active_count: 2
  -  noboost:
       algorithms:
         htmrl:
           boost_strength: 0.0
  -  shuffle:
       env:
         shuffle: 1
       algorithms:
         eps:
           enabled: 1
           e: 0.01
