general:
  repeats: 1
  steps: 350000
env:
  name: Sanity
  size: 20
  arms: 4
algorithms:
  htmrl:
      input_size: 400
      input_sparsity: 0.1
      boost_strength: 1.0
      only_reinforce_selected: 1
      reward_scaled_reinf: 1
      normalized_rewards: 0
      boost_scaled_reinf: 0
      boost_anneal: False

  #eps:
  #    e: 0.1
  random:

experiments:
  #- default:
  #- rewscaled:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #- normalized:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #-  only_selected:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #        only_reinforce_selected: 1
  #-  boosted:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #        only_reinforce_selected: 1
  #        boost_strength: 1.0  
  -  s20:
      env:
        size: 20
      algorithms:
        htmrl:
          input_size: 400
  -  s50:
      env:
        size: 50
      algorithms:
        htmrl:
          input_size: 1000
  -  s250:
      env:
        size: 250
      algorithms:
        htmrl:
          input_size: 5000
  -  s1000:
      env:
        size: 1000
      algorithms:
        htmrl:
          input_size: 20000
  -  s1500:
      env:
        size: 1500
      algorithms:
        htmrl:
          input_size: 30000
