general:
  repeats: 20
  steps: 500000
env:
  name: Sanity
  size: 20
  arms: 4
algorithms:
  htmrl:
      input_size: 400
      cell_count: 2048
      active_count: 40
      boost_strength: 1.0
      only_reinforce_selected: 1
      reward_scaled_reinf: 1
      normalized_rewards: 0
      boost_scaled_reinf: 0
      boost_until: 500000
      reward_window: 1000

experiments:
  -  a4:
      dummy: 0
  -  a10:
      env:
        arms: 10
  -  a30:
      env:
        arms: 30
  -  a100:
      env:
        arms: 100
  -  a300:
      env:
        arms: 300
  -  a1024:
      env:
        arms: 1024
