general:
  repeats: 1
  steps: 250000
env:
  name: Sanity
  size: 1000
algorithms:
  htmrl:
      input_size: 20000
      input_sparsity: 0.1
      boost_strength: 0.0
      only_reinforce_selected: 0
      reward_scaled_reinf: 0
      normalized_rewards: 0
      boost_scaled_reinf: 0
      boost_anneal: False

  #eps:
  #    e: 0.1
  random:

experiments:
  #- default:
  #- rewscaled:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #- normalized:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #-  only_selected:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #        only_reinforce_selected: 1
  -  boosted:
      algorithms:
        htmrl:
          reward_scaled_reinf: 1
          normalized_rewards: 1
          only_reinforce_selected: 1
          boost_strength: 1.0
