general:
  repeats: 1
  steps: 500000
env:
  name: Sanity
  size: 20
  arms: 4
algorithms:
  htmrl:
      input_size: 400
      input_sparsity: 0.1
      boost_strength: 1.0
      only_reinforce_selected: 1
      reward_scaled_reinf: 1
      normalized_rewards: 0
      boost_scaled_reinf: 0
      boost_anneal: False

  #eps:
  #    e: 0.1
  random:

experiments:
  #- default:
  #- rewscaled:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #- normalized:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #-  only_selected:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #        only_reinforce_selected: 1
  #-  boosted:
  #    algorithms:
  #      htmrl:
  #        reward_scaled_reinf: 1
  #        normalized_rewards: 1
  #        only_reinforce_selected: 1
  #        boost_strength: 1.0  
  -  a4:
      dummy: 0
  -  a10:
      env:
        arms: 10
  -  a30:
      env:
        arms: 30
  -  a100:
      env:
        arms: 100
  -  a300:
      env:
        arms: 300
  -  a1024:
      env:
        arms: 1024
