general:
  repeats: 20
  steps: 500000
env:
  name: Sanity
  size: 20
  arms: 4
algorithms:
  htmrl:
      input_size: 400
      cell_count: 2048
      active_count: 40
      boost_strength: 1.0
      only_reinforce_selected: 1
      reward_scaled_reinf: 1
      normalized_rewards: 0
      boost_scaled_reinf: 0
      boost_until: 500000
      reward_window: 1000

experiments:
  -  s4:
      env:
        size: 4
      algorithms:
        htmrl:
          input_size: 80
  -  s16:
      env:
        size: 16
      algorithms:
        htmrl:
          input_size: 320
  -  s64:
      env:
        size: 64
      algorithms:
        htmrl:
          input_size: 1280
  -  s256:
      env:
        size: 256
      algorithms:
        htmrl:
          input_size: 5120
  -  s1024:
      env:
        size: 1024
      algorithms:
        htmrl:
          input_size: 20480
