general:
  repeats: 20
  steps: 500000
env:
  name: Sanity
  size: 20
  arms: 4
algorithms:
  htmrl:
      input_size: 400
      cell_count: 2048
      active_count: 40
      boost_strength: 1.0
      only_reinforce_selected: 1
      reward_scaled_reinf: 1
      normalized_rewards: 0
      boost_scaled_reinf: 0
      boost_until: 500000
      reward_window: 1000

experiments:
  -  a4:
      dummy: 0
  -  a16:
      env:
        arms: 16
  -  a64:
      env:
        arms: 64
  -  a256:
      env:
        arms: 256
  -  a1024:
      env:
        arms: 1024
